# Salesforce Connected App — OAuth2 JWT Bearer flow
salesforce.username=vbolisetti.fd61c459bf@salesforce.com
salesforce.consumerKey=![Jz55ByYyrpTzcwrCW+pz2riLN8LD/QtUhzeBPpH5+J/7OOLlbKKBkaEDcw2ek7ZFRmGVnU0xyeVSmMcXv50c6C7Mi1/l504p1McdX8Cx3CoAn4N94GO1PowNmN+tGSWi]
salesforce.instance=storm-c8f46d3e4eda65.my.salesforce.com
salesforce.tokenEndpoint=https://login.salesforce.com/services/oauth2/token
salesforce.keystore.path=plantiq-keystore.jks
salesforce.keystore.password=![tLzrR1D+b4mt7afvjUNfwA==]
salesforce.keystore.alias=plantiq

# Slack incoming webhook
slack.webhook.host=hooks.slack.com
slack.webhook.path=![o9qOUe8pO1dZ7x8gNkkUUJL9g/R3RFaMiywdO57LloXL1RsS5VhheGXZdQt77Txx+6/M7O53519ggjyUN+omOA==]

# HTTP listener
http.listener.host=0.0.0.0
http.listener.port=8081

# MCP server listener
mcp.listener.port=8082
mcp.api.key=![cWItTnDPXyFse5VwpNNPIvDTWS4oU4orinUmRtfg9Lc9lZFVYLdHNeIBotcQ4rCsTC+7TX4/Sbb16svhKidmAZPQvY5EWCcooDgVM/w23+g=]

# AgentFabric management API listener
agentfabric.listener.port=8083

