# Salesforce Connected App — OAuth2 JWT Bearer flow
salesforce.username=vbolisetti.fd61c459bf@salesforce.com
salesforce.consumerKey=![wsYryMd1qc9csbFGHDMNoIWv/pd8oMF+2ixwi9f8r56KjfjoEgBt2xUXeMI5Y4Qo35p/UETBjQCkh4gQ6vEkCdK9I8zZ5g0lsREoOOEgUjYYz38e3nOCTM/hn7OGo71sSeFlCmv/MNscuBJEBALyrQ==]
salesforce.instance=storm-c8f46d3e4eda65.my.salesforce.com
salesforce.tokenEndpoint=https://login.salesforce.com/services/oauth2/token
salesforce.keystore.path=plantiq-keystore.jks
salesforce.keystore.password=![LPmdoyUwLGVr+tHmqm5YjkH0n2rMT6ZT+QbXcoKuV1c=]
salesforce.keystore.alias=plantiq

# Slack incoming webhook
slack.webhook.host=hooks.slack.com
slack.webhook.path=![OCVfW1fALwsBCmUDml326s8TO6BVhgpCRVWaWUo90/vWFE9X2ObC/xN25Izm5xCBoA7fOy2IBPfNRAOqsOwo8ptXpLpHuSHa7+OvLC+Ejh0=]

# HTTP listener
http.listener.host=0.0.0.0
http.listener.port=8081

# MCP server listener
mcp.listener.port=8082
mcp.api.key=![UpWU+CRhgESFgUhwJx3aOg5XbCyPMWk+b5qPA2dHP7P34qHLs9faglHaWLvHFm7aJ7Cxn0PUHkrlQwNGuxgDFhotOmGt9tjqKU7GO4xEQbvLsmuzWpYKamEXI5ufEq6a]

# AgentFabric management API listener
agentfabric.listener.port=8083

# TLS keystore for local HTTPS listeners (MCP + AgentFabric)
tls.keystore.path=plantiq-keystore.jks
tls.keystore.password=![QJtLnerANRsRKbv+PMbeEieiMOB75wHcTcEZmMEoraI=]
tls.keystore.keyPassword=![/GMrAnuFhoWQFpfSwC4rQ9oJWwsL/Lbc/7TklUm7E78=]
